### ISSUE TITLE
How is this related to AI using RL?

### ISSUE THREAD

**Issue by GeorgeS2019** [JarkkoPar/Utility_AI#1]
Will be interesting to see a working demo to evaluate if this approach has more advantages compared to e.g. a Godot4 RL framework with sensors, actuators for mediating environmental **states** and **rewards** to formulate **actions** for NPC

**Comment by GeorgeS2019** [comment]
https://github.com/JarkkoPar/Utility_AI_GDExtension

**Comment by JtotheThree** [comment]
It's not related at all. Utility AI is a traditional game "ai" architecture, it's not designed for learning. Godot RL is meant for researching game ai using Machine Learning and it's not a practical thing to use outside of research really.

**Comment by JarkkoPar** [comment]
Thanks @JtotheThree , I missed to answer this question entirely. I am sorry that you had to wait for a response @GeorgeS2019. 

@JtotheThree is exactly correct, Utility AI GDExtension is about *authored* behaviours and there is no machine learning going on here. In games the "AI" needs to react to events in a game in a predictable way and (usually) create fun and challenging gameplay experiences to the player. Game AI is therefore about creating a logical set of rules for the AI agents to follow, trying to make it so that it is easy to understand the flow of the rules for the player and the designers, and to make it as easy as possible to the designers to tweak and edit those rules.

In machine learning based AI, the rules the AI follows are basically a black box that is created by training the AI-model. Tweaking and changing the "rule set" of the AI agent will require more training, and the training itself can face the same challenges one may face when training a dog: if you do it wrong, it may learn the wrong thing. 

That said, I may add a neural network reasoning node somewhere down the line just because it's fun to make neural networks and maybe some may find use for it. Maybe some organic-feeling and more unpredictable behaviour selection for an animal or alien enemy, or something. It won't be anywhere near the amazing work the Godot RL  agents contributors have done, but rather a single node with configurable inputs, outputs and a neural net that can be trained.

**Comment by GeorgeS2019** [comment]
@JarkkoPar 

Could you consider supporting **GDExtension c# bindings** to [Utility_AI_GDExtension](https://github.com/JarkkoPar/Utility_AI_GDExtension)

using proposals described [here ](https://github.com/godotengine/godot-proposals/discussions/7024)?

**Comment by JarkkoPar** [comment]
I'm not that familiar with creating C# bindings so I'd rather wait until there is a recommended way of creating them. 
To support those who want to use the extension with C#, I'm actually considering making a version of it entirely in C# with the goal of minimizing the need to go across "language borders". 

I don't have any research or numbers to back the following claim up nor have I thought up yet the design, but my intuitive thinking is that traversing the AI trees within gdextension and calling any script code in C# whenever needed by the nodes has to pass through some glue code every time a C# script is accessed from the C++ code. Having all of it in C# would eliminate the need to run any glue code and come with the added benefit that extending the classes would be very easy.
